project_id = "mi-llama"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false

[experimental.pgdelta]
enabled = true
